# Generated by Django 5.1.6 on 2025-03-30 09:14

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the patient', primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text="Patient's email for login", max_length=254, unique=True)),
                ('name', models.CharField(help_text="Patient's full name", max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Non-binary', 'non-binary'), ('Other', 'other'), ('Prefer not to say', 'prefer not to say')], help_text='Male, Female, Non-binary, Other, or Prefer not to say.', max_length=20)),
                ('age', models.IntegerField(help_text="Patient's age")),
                ('health_conditions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text="List of existing health conditions (e.g. 'Type 2 Diabetes', 'Hypertension')", null=True, size=None)),
                ('health_goals', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text="List of patient’s health goals (e.g. 'Lose weight', 'Improve sleep')", null=True, size=None)),
                ('motivators', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text="Key personal motivators for health (e.g. 'Family', 'Longevity')", null=True, size=None)),
                ('provider_code', models.CharField(help_text='Unique code linking the patient to a provider', max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='Date when user created the account.')),
                ('active_status', models.BooleanField(default=True, help_text='Whether user is currently active.')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('age__gte', 0), ('age__lte', 120)), name='valid_age_range')],
            },
        ),
    ]
