# Generated by Django 5.1.6 on 2025-03-30 09:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for category', primary_key=True, serialize=False)),
                ('category_name', models.CharField(help_text='Name of the chronic condition category', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the category', null=True)),
            ],
        ),
    ]
