# Generated by Django 5.1.7 on 2025-03-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='valid_age_range',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Non-binary', 'non-binary'), ('Other', 'other'), ('Prefer not to say', 'prefer not to say'), ('Female', 'female'), ('Male', 'male')], help_text='Male, Female, Non-binary, Other, or Prefer not to say.', max_length=20),
        ),
    ]
