# Generated by Django 5.1.7 on 2025-03-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_user_valid_age_range_alter_user_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='movivators',
            new_name='motivators',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Non-binary', 'non-binary'), ('Other', 'other'), ('Prefer not to say', 'prefer not to say')], help_text='Male, Female, Non-binary, Other, or Prefer not to say.', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('age__gte', 0), ('age__lte', 120)), name='valid_age_range'),
        ),
    ]
