# Generated by Django 5.1.7 on 2025-03-27 09:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_user_health_conditions_alter_user_health_goals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='health_conditions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text="List of existing health conditions (e.g. 'Type 2 Diabetes', 'Hypertension')", null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='health_goals',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text="List of patient’s health goals (e.g. 'Lose weight', 'Improve sleep')", null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='motivators',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text="Key personal motivators for health (e.g. 'Family', 'Longevity')", null=True, size=None),
        ),
    ]
